# Generated by Django 5.0.7 on 2024-07-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phon_number',
            new_name='phone_number',
        ),
    ]
